### ISSUE TITLE
Update part number

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/iLogic-Vault#19] opened 2022-06-14 12:30 UTC
Go to method:
 public string GetFileCopyBySourceFileNameAndNewName(string VaultFullFileName, string NewFileNameNoExt, bool CheckOut = true, bool UpdatePartNumber = true))

Create a copy of file in Vault and you should get an error like this:
![image](https://user-images.githubusercontent.com/61918020/173576985-3fe7253c-310f-4ec8-86e0-d9188d9d170f.png)

I add try catch method to catch exception and return something, because if it's not done then iLogic wait for answer what is nothing because exceptions occurs (if i understand correctly).

**Comment by koechlm** [comment] 2022-06-14 15:41
Hi Dariusz, I cannot reproduce an issue here. I run the sample rule delivered with the package in two scenarios:
- The source file is an IPT. No issue to expect, as the new file is available for checkout, and the options to check out and update part number will work
- The source file is a *.idw.pdf design representation file: Update part number and check-out options will fail as the design representation is locked in its initial state. Anyway, my sample rule runs without any issue: `Dim mVaultFile As String = iLogicVault.GetFileCopyBySourceFileNameAndNewName("$/Designs/Inventor Sample Data/Fishing Rod Model/001002.idw.pdf", mNewFileName, True, True) 'optionally add the mNumInput variable; note - new file name must not contain an extension! The check-out option is True as default; set to False or remove.
	If mVaultFile Is Nothing Then
		Logger.Error("File copy not created; validate source file can be found and new file name." )
	Else
		Logger.Info("File " & mVaultFile & " created As copy.")
			'add next action using the downloaded file here, e.g. Component.Replace("Part1:1", mVaultFile, True)
	End If`
The log and result in Vault: Log: `INFO|File C:\PDMC-Sample\Designs\Inventor Sample Data\Fishing Rod Model\5abc53d7-0379-49fa-b736-4a61df064bd6.pdf created As copy.`
![image](https://user-images.githubusercontent.com/19150039/173619296-1f740efa-e9d3-49fc-8956-f3ea3ff6f5d6.png)

So, I am not sure what your intent is? What might happen is that the file iteration is not created; in this case, the UpdateProperties will fail with an unhandled exception. Instead of using a Try-Catch block, I suggest handling the case by validating the new (copy) file iteration before.

**Comment by DariuszMrozik** [comment] 2022-06-17 14:10
I can't reproduce it now - i don't know why. If it will be able to reproduce I will try to make a screencast.

**Comment by koechlm** [comment] 2022-12-06 09:06
Closing as no additional information or repro provided.

**Closed as not planned by koechlm** 2022-12-06 09:06 UTC
Labels: information gathering
